# Generated by Django 2.2.4 on 2020-10-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clusteringkr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('label', models.BigIntegerField(blank=True, null=True)),
                ('trading_value', models.BigIntegerField(blank=True, db_column='Trading Value', null=True)),
            ],
            options={
                'db_table': 'clusteringkr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('open', models.BigIntegerField(blank=True, db_column='Open', null=True)),
                ('high', models.BigIntegerField(blank=True, db_column='High', null=True)),
                ('low', models.BigIntegerField(blank=True, db_column='Low', null=True)),
                ('close', models.BigIntegerField(blank=True, db_column='Close', null=True)),
                ('volume', models.BigIntegerField(blank=True, db_column='Volume', null=True)),
                ('change', models.FloatField(blank=True, db_column='Change', null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Krchartdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('x0', models.TextField(blank=True, null=True)),
                ('x1', models.TextField(blank=True, null=True)),
                ('x2', models.TextField(blank=True, null=True)),
                ('x3', models.TextField(blank=True, null=True)),
                ('x4', models.TextField(blank=True, null=True)),
                ('x5', models.TextField(blank=True, null=True)),
                ('x6', models.TextField(blank=True, null=True)),
                ('x7', models.TextField(blank=True, null=True)),
                ('x8', models.TextField(blank=True, null=True)),
                ('x9', models.TextField(blank=True, null=True)),
                ('x10', models.TextField(blank=True, null=True)),
                ('x11', models.TextField(blank=True, null=True)),
                ('x12', models.TextField(blank=True, null=True)),
                ('x13', models.TextField(blank=True, null=True)),
                ('x14', models.TextField(blank=True, null=True)),
                ('x15', models.TextField(blank=True, null=True)),
                ('x16', models.TextField(blank=True, null=True)),
                ('x17', models.TextField(blank=True, null=True)),
                ('x18', models.TextField(blank=True, null=True)),
                ('x19', models.TextField(blank=True, null=True)),
                ('x20', models.TextField(blank=True, null=True)),
                ('x21', models.TextField(blank=True, null=True)),
                ('x22', models.TextField(blank=True, null=True)),
                ('x23', models.TextField(blank=True, null=True)),
                ('x24', models.TextField(blank=True, null=True)),
                ('x25', models.TextField(blank=True, null=True)),
                ('x26', models.TextField(blank=True, null=True)),
                ('x27', models.TextField(blank=True, null=True)),
                ('x28', models.TextField(blank=True, null=True)),
                ('x29', models.TextField(blank=True, null=True)),
                ('x30', models.TextField(blank=True, null=True)),
                ('x31', models.TextField(blank=True, null=True)),
                ('x32', models.TextField(blank=True, null=True)),
                ('x33', models.TextField(blank=True, null=True)),
                ('x34', models.TextField(blank=True, null=True)),
                ('x35', models.TextField(blank=True, null=True)),
                ('x36', models.TextField(blank=True, null=True)),
                ('x37', models.TextField(blank=True, null=True)),
                ('x38', models.TextField(blank=True, null=True)),
                ('x39', models.TextField(blank=True, null=True)),
                ('x40', models.TextField(blank=True, null=True)),
                ('x41', models.TextField(blank=True, null=True)),
                ('x42', models.TextField(blank=True, null=True)),
                ('x43', models.TextField(blank=True, null=True)),
                ('x44', models.TextField(blank=True, null=True)),
                ('x45', models.TextField(blank=True, null=True)),
                ('x46', models.TextField(blank=True, null=True)),
                ('x47', models.TextField(blank=True, null=True)),
                ('x48', models.TextField(blank=True, null=True)),
                ('x49', models.TextField(blank=True, null=True)),
                ('x50', models.TextField(blank=True, null=True)),
                ('x51', models.TextField(blank=True, null=True)),
                ('x52', models.TextField(blank=True, null=True)),
                ('x53', models.TextField(blank=True, null=True)),
                ('x54', models.TextField(blank=True, null=True)),
                ('x55', models.TextField(blank=True, null=True)),
                ('x56', models.TextField(blank=True, null=True)),
                ('x57', models.TextField(blank=True, null=True)),
                ('x58', models.TextField(blank=True, null=True)),
                ('x59', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'krchartdata',
                'managed': False,
            },
        ),
    ]
