# Generated by Django 2.2.4 on 2020-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringkrInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('구분', models.TextField(blank=True, null=True)),
                ('구분상세', models.TextField(blank=True, null=True)),
                ('기초지수', models.TextField(blank=True, null=True)),
                ('설명', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clusteringkr_info',
                'managed': False,
            },
        ),
    ]
